/**
 * Golden geometry cases for shared/fixtures/tier1_cases.json (docs/phases/PHASE2.md section 5).
 * Phase 3's Python geometry must reproduce every number in `geometry` to 0.1 %.
 */

import type { DesignParameters, Mission } from '../../api/types';
import { AIRFOIL_SHAPE_FALLBACK } from '../constants';
import { buildGeometry, withDefaults } from '../geometry';
import type { Geometry } from '../types';
import { roundSig } from '../units';
import { defaultMission, newProjectParameters, finalScaleMission, finalScaleParameters, quadPusherParameters } from './designs';

type Num = number | null;
type Tree = { [k: string]: Num | Num[] | Tree | Tree[] | string };

const r = (v: number): number => roundSig(v, 10);
const v3 = (v: [number, number, number]): number[] => v.map(r);

/** The geometry numbers Phase 3 must reproduce (no render primitives). */
export function geometryNumbers(g: Geometry): Tree {
  const w = g.wing;
  const t = g.tail;
  const f = g.fuselage;
  return {
    wing: {
      area_m2: r(w.area_m2),
      exposed_area_m2: r(w.exposed_area_m2),
      aspect_ratio: r(w.aspect_ratio),
      taper_ratio: r(w.taper_ratio),
      mac_mm: r(w.mac_mm),
      mac_y_mm: r(w.mac_y_mm),
      mac_x_le_mm: r(w.mac_x_le_mm),
      ac_x_mm: r(w.ac_x_mm),
      sweep_quarter_chord_deg: r(w.sweep_quarter_chord_deg),
      sweep_max_thickness_deg: r(w.sweep_max_thickness_deg),
      thickness_ratio: r(w.thickness_ratio),
      wetted_area_m2: r(w.wetted_area_m2),
      tip_le: v3(w.tip_le),
    },
    tail: {
      planform_area_m2: r(t.planform_area_m2),
      horizontal_area_m2: r(t.horizontal_area_m2),
      vertical_area_m2: r(t.vertical_area_m2),
      pitch_effective_area_m2: r(t.pitch_effective_area_m2),
      aspect_ratio: r(t.aspect_ratio),
      panel_angle_deg: r(t.panel_angle_deg),
      quarter_chord_x_mm: r(t.quarter_chord_x_mm),
      le_x_mm: r(t.le_x_mm),
      te_x_mm: r(t.te_x_mm),
      z_mm: r(t.z_mm),
      wetted_area_m2: r(t.wetted_area_m2),
      horizontal_volume_coefficient: r(t.horizontal_volume_coefficient),
      vertical_volume_coefficient: r(t.vertical_volume_coefficient),
      support_length_mm: r(t.support_length_mm),
    },
    fuselage: {
      nose_length_mm: r(f.nose_length_mm),
      tail_length_mm: r(f.tail_length_mm),
      max_cross_section_area_m2: r(f.max_cross_section_area_m2),
      equivalent_diameter_mm: r(f.equivalent_diameter_mm),
      fineness_ratio: r(f.fineness_ratio),
      wetted_area_m2: r(f.wetted_area_m2),
    },
    booms: g.booms.map((b) => ({ side: b.side, start: v3(b.start), end: v3(b.end) })),
    rotors: g.rotors.map((x) => ({ id: x.id, position: v3(x.position), diameter_mm: r(x.diameter_mm) })),
    front_rotor_x_mm: r(g.front_rotor_x_mm),
    rear_rotor_x_mm: r(g.rear_rotor_x_mm),
    tilt_hinge_x_mm: g.tilt_hinge_x_mm === null ? null : r(g.tilt_hinge_x_mm),
    landing_gear_bottom_z_mm: r(g.landing_gear_bottom_z_mm),
  };
}

interface Case {
  name: string;
  description: string;
  parameters: DesignParameters;
  mission: Mission;
}

const CASES: Case[] = [
  { name: 'default_prototype', description: 'New-project default: 2.5 kg target, 1.8 m span, front tilt, inverted V tail, battery at 290 mm (schema v2 defaults).', parameters: newProjectParameters(), mission: defaultMission() },
  { name: 'final_24kg', description: 'Final-scale case: default lengths x (24/2.5)^(1/3), 35 mm booms, Li-ion 12S8P, 24 kg target.', parameters: finalScaleParameters(), mission: finalScaleMission() },
  { name: 'quad_pusher', description: 'Default design as quad + pusher.', parameters: quadPusherParameters(), mission: defaultMission() },
];

/** The full fixture document. */
export function buildGoldenFixture(): Tree {
  return {
    description:
      'Tier 1 geometry golden cases. Generated by frontend/src/engine/fixtures.test.ts (UPDATE_FIXTURES=1). Phase 3 Python geometry must reproduce every number under "geometry" to 0.1 % relative (absolute 1e-6 for zeros). Conventions: docs/ENGINE.md "Geometry".',
    tolerance_relative: 0.001,
    airfoil_shapes_used: {
      note: 'Geometry uses these built-in thickness ratios and positions (fraction of chord) when no airfoil summary is passed.',
      sd7037: { t: AIRFOIL_SHAPE_FALLBACK.sd7037.t, xt: AIRFOIL_SHAPE_FALLBACK.sd7037.xt },
      naca0009: { t: AIRFOIL_SHAPE_FALLBACK.naca0009.t, xt: AIRFOIL_SHAPE_FALLBACK.naca0009.xt },
    },
    cases: CASES.map((c) => ({
      name: c.name,
      description: c.description,
      parameters: withDefaults(c.parameters) as unknown as Tree,
      mission: c.mission as unknown as Tree,
      geometry: geometryNumbers(buildGeometry(c.parameters, { render: false })),
    })),
  };
}
